services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - 'data:/data'
    environment:
      - 'MONGO_INITDB_DATABASE=duckling'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

volumes:
  data: {}